# Generated by Django 3.2.12 on 2022-03-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_usersignup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='pwd',
            new_name='password',
        ),
    ]
