# Generated by Django 3.0 on 2022-03-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddress',
            new_name='Address',
        ),
    ]
