# Generated by Django 3.0 on 2022-04-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220408_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_product', models.CharField(default=0, max_length=500, null=True)),
                ('total_amoumt', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PN', 'Panding'), ('AC', 'Accepted'), ('OD', 'Out for Delivery')], default='panding', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('addressId', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Address')),
                ('product', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('userId', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.UserSignUp')),
            ],
        ),
    ]
