# Generated by Django 3.0 on 2022-04-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mark',
            field=models.CharField(choices=[('DD', 'Deal of the day'), ('BS', 'Best Seller')], default='null', max_length=20, null=True),
        ),
    ]
