# Generated by Django 3.0 on 2022-04-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mark',
            field=models.CharField(choices=[('--', '-----------'), ('DD', 'Deal of the day'), ('BS', 'Best Seller')], default='null', max_length=20, null=True),
        ),
    ]
